

const supportBankCodes = [ '108',
    '118',
    '803',
    '805',
    '806',
    '808',
    '809',
    '810',
    '812',
    '815',
    '816',
    '004',
    '006',
    '007',
    '008',
    '009',
    '012',
    '016',
    '021',
    '050',
    '052',
    '081' ]

const supportBankNames = [ '陽信銀行',
    '板信銀行',
    '聯邦銀行',
    '遠東銀行',
    '元大銀行',
    '玉山銀行',
    '凱基銀行',
    '星展銀行',
    '台新銀行',
    '日盛銀行',
    '安泰銀行',
    '台灣銀行',
    '合作金庫',
    '第一銀行',
    '華南銀行',
    '彰化銀行',
    '富邦銀行',
    '高雄銀行',
    '花旗銀行',
    '台灣企銀',
    '渣打銀行',
    '滙豐銀行' ]

// const validBankDataArray = [
//     '108','陽信銀行','陽信','118','板信銀行'
// ]

const helpArray = ['幣別對照','']

const currentChineseNameToEng = {
    '美金': 'USD',
    '歐元': 'EUR',
    '日幣': 'JPY',
    '英鎊': 'GBP',
    '港幣': 'HKD',
    '加拿大幣': 'CAD',
    '新加坡幣': 'SGD',
    '瑞士法郎': 'CHF',
    '瑞典幣': 'SEK',
    '南非幣': 'ZAR',
    '泰幣': 'THB',
    '紐西蘭幣': 'NZD',
    '人民幣': 'CNY',
    '新台幣': 'TWD',
    '韓元': 'KRW',
    '馬來幣': 'MYR',
    '菲國比索': 'PHP',
    '印尼幣': 'IDR',
    '越南盾': 'VND'
}

const bankNameToBankCodeDict = {
    '108':'108',
    陽信銀行:'108',
    陽信:'108',
    '118':'118',
    板信銀行:'118',
    板信:'118',
    '803':'803',
    聯邦銀行:'803',
    聯邦:'803',
    '805':'805',
    遠東銀行:'805',
    遠東:'805',
    '806':'806',
    元大銀行:'806',
    元大:'806',
    '808':'808',
    玉山銀行:'808',
    玉山:'808',
    '809':'809',
    凱基銀行:'809',
    凱基:'809',
    '810':'810',
    星展銀行:'810',
    星展:'810',
    '812':'812',
    台新銀行:'812',
    臺新銀行:'812',
    臺新:'812',
    台新:'812',
    '815':'815',
    日盛銀行:'815',
    日盛:'815',
    '816':'816',
    安泰銀行:'816',
    安泰:'816',
    '004':'004',
    台灣銀行:'004',
    臺灣銀行:'004',
    台銀:'004',
    臺銀:'004',
    '006':'006',
    合作金庫:'006',
    合庫:'006',
    '007':'007',
    第一銀行:'007',
    一銀:'007',
    第一:'007',
    第一銀:'007',
    '008':'008',
    華南銀行:'008',
    華南:'008',
    '009':'009',
    彰化銀行:'009',
    彰化:'009',
    彰銀:'009',
    '012':'012',
    富邦銀行:'012',
    富邦:'012',
    '016':'016',
    高雄銀行:'016',
    高雄:'016',
    '021':'021',
    花旗銀行:'021',
    花旗:'021',
    '050':'050',
    台灣企銀:'050',
    台灣企銀:'050',
    台企銀:'050',
    臺企銀:'050',
    '052':'052',
    渣打銀行:'052',
    渣打:'052',
    '081':'081',
    滙豐銀行:'081',
    滙豐:'081',
}


// const array = Object.keys(bankNameToBankCodeDict)
// console.log(array)


const currencyETCDict = { USD: '美金',
    EUR: '歐元',
    JPY: '日幣',
    GBP: '英鎊',
    HKD: '港幣',
    AUD: '澳幣',
    CAD: '加拿大幣',
    SGD: '新加坡幣',
    CHF: '瑞士法郎',
    SEK: '瑞典幣',
    ZAR: '南非幣',
    THB: '泰幣',
    NZD: '紐西蘭幣',
    CNY: '人民幣',
    TWD: '新台幣',
    KRW: '韓元',
    MYR: '馬來幣',
    PHP: '菲國比索',
    IDR: '印尼幣',
    VND: '越南盾',
}

const currencyETFDict = { USD: '🇺🇸',
    EUR: '🇪🇺',
    JPY: '🇯🇵',
    GBP: '🇬🇧',
    HKD: '🇭🇰',
    AUD: '🇦🇺',
    CAD: '🇨🇦',
    SGD: '🇸🇬',
    CHF: '🇨🇭',
    SEK: '🇸🇪',
    ZAR: '🇿🇦',
    THB: '🇹🇭',
    NZD: '🇳🇿',
    CNY: '🇨🇳',
    TWD: '🇹🇼',
    KRW: '🇰🇷',
    MYR: '🇲🇾',
    PHP: '🇵🇭',
    IDR: '🇮🇩',
    VND: '🇻🇳',
}

const supportBankInfo =  [
    { bankCode: '108', bankName: '陽信銀行' },
    { bankCode: '118', bankName: '板信銀行' },
    { bankCode: '803', bankName: '聯邦銀行' },
    { bankCode: '805', bankName: '遠東銀行' },
    { bankCode: '806', bankName: '元大銀行' },
    { bankCode: '808', bankName: '玉山銀行' },
    { bankCode: '809', bankName: '凱基銀行' },
    { bankCode: '810', bankName: '星展銀行' },
    { bankCode: '812', bankName: '台新銀行' },
    { bankCode: '815', bankName: '日盛銀行' },
    { bankCode: '816', bankName: '安泰銀行' },
    { bankCode: '004', bankName: '台灣銀行' },
    { bankCode: '006', bankName: '合作金庫' },
    { bankCode: '007', bankName: '第一銀行' },
    { bankCode: '008', bankName: '華南銀行' },
    { bankCode: '009', bankName: '彰化銀行' },
    { bankCode: '012', bankName: '富邦銀行' },
    { bankCode: '016', bankName: '高雄銀行' },
    { bankCode: '021', bankName: '花旗銀行' },
    { bankCode: '050', bankName: '台灣企銀' },
    { bankCode: '052', bankName: '渣打銀行' },
    { bankCode: '081', bankName: '滙豐銀行' }
    ]


const MESSAGE_TYPE_BANK_RATE = 'messageTypeBankRate'
const MESSAGE_TYPE_BEST_RATE = 'messageTypeBestRate'
const MESSAGE_TYPE_PASS = 'messageTypePass'
const MESSAGE_TYPE_WORNG_COMMAND = 'messageTypeWorngCommand'
const MESSAGE_TYPE_NO_MATCH = 'messageTypeNoMatch'


module.exports = {
    supportBankInfo,
    bankNameToBankCodeDict,
    currencyETCDict,
    currencyETFDict,
    MESSAGE_TYPE_BANK_RATE,
    MESSAGE_TYPE_BEST_RATE,
    MESSAGE_TYPE_PASS,
    MESSAGE_TYPE_WORNG_COMMAND,
    MESSAGE_TYPE_NO_MATCH
}